version: '3.8'

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8006"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
